language: node_js
sudo: false
node_js:
  - "node"
  - "10"
  - "8"
  - "6"
cache: npm
os:
  - osx
  - precise
  - xenial
  - windows
script:
  - npm test
notifications:
  email:
    on_success: never
    on_failure: never
